name: Build and Deploy to digitalOcean

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build
        run: go build -v ./...

      - name: Copy SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to DigitalOcean Droplet
        run: scp -r app root@142.93.135.10:/path/to/destination
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}